const data = {
    products: [
      {
        _id: '1',
        name: 'Smart Watch',
        category: 'Watch',
        image: '/images/product1.jpg',
        price: 35,
        countInStock: 10,
        brand: 'M3',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Laptop',
        category: 'Tech',
        image: '/images/product2.jpg',
        price: 60,
        countInStock: 20,
        brand: 'Dell',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Android Mobile',
        category: 'Mobile',
        image: '/images/product3.jpg',
        price: 40,
        countInStock: 0,
        brand: 'Lacoste',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Gaming Mouse',
        category: 'Tech',
        image: '/images/product4.jpg',
        price: 25,
        countInStock: 15,
        brand: 'Banda',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Nintendo Switch',
        category: 'Tech',
        image: '/images/product5.jpg',
        price: 259.5,
        countInStock: 5,
        brand: 'Nintendo',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      
      
    ],
  };
  export default data;